language: node_js
sudo: required
services: docker
script:
  - docker build .
deploy:
  provider: npm
  email: rzr@users.sf.net
  api_key:
    secure: b5wy0AB13TToSmNHxCuPlUk8bmzFRKYpqupsIdk6FqwPDVsepbDXNPqBAZ2xZ7clpNk3NS07Sz5Ew/2r5th3qhJ8ZWISU9rxXEmmINGu0/JLJJzZxaw4Vm13RR0iWWCCHbVEaWr4CAUxtTgGI7WEy8zoZv40hZKQceX89sFlu1Hng4nY8GRnQnf8IO9+vjBeznKHiIEn9LBSc3zG9DUonZKneqibHwSPD++FyWmvbWWdfLbmlfouTHzDH/JltuNtTx4vwkBgrDqlmqdwXQQ5QzqzUxvWTraAycGJtw+GzRgNHO7kEhXRZWFHfZctCv8Mu7aQ+KYKX/9qjoqt3DR7blrbq2P9NEkUIwRpLLpje90Fio20734V+zuIA0Ld1UU6pTnK725JEizaWe23X3ZuhzrT0Eq3IdVMP7d6+/Suj/BleOD4+ywthhw3602eU9y38flLkHy22NjiDFTV/80tEnKT3HxWEVcBdj/BIccRJHqQm/hu7iFeZn3/VRgGH1/SUxutIvySGDYNKKOoy4cU1lUBh/k/efDrU532/V0mitAdPK1cIQZvTIho/0aYtfDyqql7Bgh0RkxoaBxudHVzTyYiWy4R/Eve7i9h6MuoJQWGMLiWs/NMPkriXPN15E7iNaNsDlbySoIPXNUnPTpFgPzyU/9yGn/QWmymGRvBE7s=
  on:
    tags: true
    repo: rzr/iotjs-express
