dist: trusty
language: node_js
sudo: required
services: docker
script:
- docker build .
deploy:
  provider: npm
  email: rzr@users.sf.net
  secure: "UbQ5gpJsCual5EJuLEY4Mi9HrVvPD7tjWZslPmOvUfEW18LBXr/UDbHFDAKtoou8APsTowE8vf0IJvhYXGXE1oOl+GvMiwmh20N908ThIWTLxFBJ6L5HxowuHtpiap3Gs8wYrDGTF1N6WoIb66oky8xYsWb3nBV6WnVS15huTz+dpUbwVrhY15Fy+61QZ+qUNrfWMwbPshuo9YtnYihi5rY0Pq1pV4Q0864BRrnS0p7SKyHDUTbXDxdfiKXssa2GeGvHRMe3vasyj3y/6eLB09EJHUl5xwfBc81pOElIOwj8pavz6LPRMsv7CAy7r10ngdXxnCDzDvS80tZhrNVp301CsjNNoYVb8eEudAD3vOyGlyC8nAF0WyMlk9KW6P3XvOelpqq/yUhHDnSx3SGBPSuBl9wKoU4JtKy3sGtzgs501SP8taqZrH2UhD8No90HCx7K/UZ/vtwBMQ9s/m1KZ1f5MAKg4IYEE/kQegnYdXeOFjILy55sUnioVO9Db+LW3Q1PdWqjegmvveVvQ85wRZ+KXz4ToUJ0CVCjIOLMkea1Uvo8mywfRNNybAAfOuR/3TtNBtpHt3xQM0aQiNsS2yHgV/FVmq5z6JzniiAIrHttUBQdKhopLoRaoZO40wotoKeglxZSUoSa0KDlqos2oguAelb/p9j82UdlQrqciHQ="
  on:
    tags: true
    repo: rzr/iotjs-express
