apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ${name}
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    - ${domain}
    secretName: letsencrypt-staging
  rules:
  - host: ${host}
    http:
      paths:
      - backend:
          serviceName: ${name}
          servicePort: ${port}
