#YAML
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: iotjs-express
  name: iotjs-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iotjs-express
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: iotjs-express
    spec:
      containers:
      - image: rzrfreefr/iotjs-express:latest
        name: iotjs-express
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: iotjs-express
  name: iotjs-express
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: iotjs-express
  type: NodePort
status:
  loadBalancer: {}
---
