apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: iotjs-express
  name: iotjs-express
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: iotjs-express
  type: NodePort
status:
  loadBalancer: {}
