apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ${name}
spec:
  secretName: ${name}-crt
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    namespace: cert-manager
  commonName: ${name}.${domain}
  dnsNames:
  - ${name}.${domain}
